### PR TITLE
[Doc] sync AMQP1_0 connector docs to hub

### PR DESCRIPTION
**Pull request by Anonymitaet**
Preview link: https://staging--streamnative-hub.netlify.app/connectors/amqp-1-0-sink/v2.7.1.1/

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@tuteng  after executing the command `curl -X POST -d '0415' https://api.netlify.com/build_hooks/60541a91fa1298719f828515`under the directory `pulsar-hub`, the AMQP1_0 connector guide is not shown on the preview.

P.S. I corrected the metadata in amqp docs for master and branch-2.7.1 yesterday.

Did I do something wrong? Thanks for your reply.

**Comment by Anonymitaet** [comment]
@tuteng FYI: just as we discussed, I used the “old” method to copy contents to Hub repo in this PR.

**Review by tuteng — COMMENTED** [review]
Please rename the directory from 2.7.1.1 to v2.7.1.1

**Comment by Anonymitaet** [comment]
@tuteng OK, done.

**Comment by Anonymitaet** [comment]
@tuteng the preview is good to go, I'll merge this PR.

**Pull request merged**
